import {
  BarChart3,
  ArrowRight,
  BrainCircuit,
  Database,
  Activity,
} from "lucide-react";

export default function AnalyticsDashboard() {
  return (
    <div className="min-h-screen bg-gradient-to-br from-cyan-100 via-sky-50 to-indigo-100">

      {/* Hero Section */}

      <section className="max-w-7xl mx-auto px-10 py-16">

        <div className="grid grid-cols-2 gap-12 items-center">

          {/* Left */}

          <div>
            <h1 className="text-6xl font-bold text-slate-900 leading-tight">

              Analytics For

              <span className="text-cyan-600">
                {" "}
                Corporate Documents
              </span>

            </h1>

            <p className="text-slate-600 text-lg leading-8 mt-6">

              Monitor It's performance, analyze document usage,
              track user activities and generate intelligent
              business insights from one centralized dashboard.

            </p>

          </div>

          {/* Right */}

          <div className="bg-white rounded-3xl shadow-2xl p-10">

            <div className="bg-gradient-to-br from-cyan-500 to-blue-600 rounded-3xl p-10 text-white">

              <h2 className="text-3xl font-bold mt-6">

                Analytics

              </h2>

              <p className="mt-4 text-cyan-100 leading-7">

                Corporate insights powered by intelligence systems for business decisions.

              </p>

              <div className="grid grid-cols-2 gap-5 mt-10">

                <div className="bg-white/20 rounded-2xl p-5">

                  <Database size={32} />

                  <p className="mt-3 font-semibold">

                    1,250 Documents

                  </p>

                </div>

                <div className="bg-white/20 rounded-2xl p-5">

                  <Activity size={32} />

                  <p className="mt-3 font-semibold">

                    98.7% Accuracy

                  </p>

                </div>

              </div>

            </div>

          </div>

        </div>

      </section>
            {/* Feature Cards-------------2nd parts--------------- */}

      <section className="max-w-7xl mx-auto px-10 pb-16">

        <div className="grid grid-cols-3 gap-8">

          {/* Card 1 */}

          <div className="bg-white rounded-3xl p-8 shadow-lg hover:shadow-2xl transition duration-300 hover:-translate-y-2">

            <div className="w-16 h-16 rounded-2xl bg-cyan-100 flex items-center justify-center">

              <BarChart3 className="text-cyan-600" size={34} />

            </div>

            <h2 className="text-2xl font-bold mt-6 text-slate-800">

              System Reports

            </h2>

            <p className="mt-4 text-slate-600 leading-7">

              Generate smart reports and visualize system
              analytics with Intelligence insights.

            </p>

          </div>

          {/* Card 2 */}

          <div className="bg-white rounded-3xl p-8 shadow-lg hover:shadow-2xl transition duration-300 hover:-translate-y-2">

            <div className="w-16 h-16 rounded-2xl bg-green-100 flex items-center justify-center">

              <Activity className="text-green-600" size={34} />

            </div>

            <h2 className="text-2xl font-bold mt-6 text-slate-800">

              Live Monitoring

            </h2>

            <p className="mt-4 text-slate-600 leading-7">

              Monitor user activities and performance
              continuously with live statistics.

            </p>

          </div>

          {/* Card 3 */}

          <div className="bg-white rounded-3xl p-8 shadow-lg hover:shadow-2xl transition duration-300 hover:-translate-y-2">

            <div className="w-16 h-16 rounded-2xl bg-purple-100 flex items-center justify-center">

              <BrainCircuit className="text-purple-600" size={34} />

            </div>

            <h2 className="text-2xl font-bold mt-6 text-slate-800">

              Intelligence Insights

            </h2>

            <p className="mt-4 text-slate-600 leading-7">

              Discover intelligent trends and recommendations
              generated by Corporate typely.

            </p>

          </div>

          {/* Card 4 */}

          <div className="bg-white rounded-3xl p-8 shadow-lg hover:shadow-2xl transition duration-300 hover:-translate-y-2">

            <div className="w-16 h-16 rounded-2xl bg-orange-100 flex items-center justify-center">

              <Database className="text-orange-600" size={34} />

            </div>

            <h2 className="text-2xl font-bold mt-6 text-slate-800">

              Secure Storage

            </h2>

            <p className="mt-4 text-slate-600 leading-7">

              Store corporatee documents securely with encrypted
              cloud infrastructure.

            </p>

          </div>

          {/* Card 5 */}

          <div className="bg-white rounded-3xl p-8 shadow-lg hover:shadow-2xl transition duration-300 hover:-translate-y-2">

            <div className="w-16 h-16 rounded-2xl bg-pink-100 flex items-center justify-center">

              <ArrowRight className="text-pink-600" size={34} />

            </div>

            <h2 className="text-2xl font-bold mt-6 text-slate-800">

              Smart Workflow

            </h2>

            <p className="mt-4 text-slate-600 leading-7">

              Automate repetitive tasks and improve team
              productivity using workflows.

            </p>

          </div>

          {/* Card 6 */}

          <div className="bg-white rounded-3xl p-8 shadow-lg hover:shadow-2xl transition duration-300 hover:-translate-y-2">

            <div className="w-16 h-16 rounded-2xl bg-indigo-100 flex items-center justify-center">

              <BarChart3 className="text-indigo-600" size={34} />

            </div>

            <h2 className="text-2xl font-bold mt-6 text-slate-800">

              Business Growth

            </h2>

            <p className="mt-4 text-slate-600 leading-7">

              Analyze business performance with interactive
              enterprise dashboards and visual metrics.

            </p>

          </div>

        </div>

      </section>

    </div>
  );
}